name: pruebas_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^5.1.3
  google_maps_flutter: ^0.5.25+3
  google_maps_webservice: ^0.0.14
  provider: ^3.1.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

 uses-material-design: true

 